openapi: 3.0.0
info:
  title: AI Assistant
  version: 1.0.0
servers:
  - url: /api
tags:
  - name: chat
    description: Chat endpoint
paths:
  /chat:
    post:
      tags:
        - chat
      summary: Chat endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatInput'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatOutput'
    delete:
      tags:
        - chat
      summary: Delete chat endpoint
      responses:
        '204':
          description: Successful response
  /travel/departures:
    get:
      tags:
        - travel
      summary: Departures endpoint
      parameters:
        - name: station
          in: query
          required: true
          schema:
            type: string
        - name: count
          in: query
          required: false
          schema:
            type: integer
        - name: departureTime
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: addJourneys
          in: query
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Departures'
        '400':
          description: Invalid request
  /travel/journey:
    get:
      tags:
        - travel
      summary: Journey endpoint
      parameters:
        - name: station
          in: query
          required: true
          schema:
            type: string
        - name: trainNumber
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Journey'
        '400':
          description: Invalid request
components:
  schemas:
    ChatInput:
      type: object
      properties:
        chat:
          type: string
      required:
        - chat
    ChatOutput:
      type: object
      properties:
        chat:
          type: string
      required:
        - chat
    Departure:
      type: object
      properties:
        trainNumber:
          type: string
        direction:
          type: string
        departureTime:
          type: string
          format: date-time
        delay:
          type: integer
          format: int64
        track:
          type: string
        category:
          type: string
        cancelled:
          type: boolean
        via:
          type: array
          items:
            type: string
        departureStatus:
          $ref: '#/components/schemas/DepartureStatusEnum'
        message:
          type: string
        journey:
          $ref: '#/components/schemas/Journey'
    DepartureStatusEnum:
      type: string
      enum:
        - ON_STATION
        - INCOMING
        - DEPARTED
        - UNKNOWN
    Departures:
      type: array
      items:
        $ref: '#/components/schemas/Departure'
    Journey:
      type: object
      properties:
        origin:
          type: string
        destination:
          type: string
        category:
          type: string
        cancelled:
          type: boolean
        trainType:
          type: string
        trainLength:
          type: integer
          format: int64
        numberOfSeats:
          type: integer
          format: int64
        stockIdentifiers:
          type: array
          items:
            type: string
        stockImageUris:
          type: array
          items:
            type: string
        crowdForecast:
          type: string
          enum:
            - UNKNOWN
            - LOW
            - MEDIUM
            - HIGH
        stops:
          type: array
          items:
            type: string