openapi: 3.0.0
info:
  title: AI Assistant
  version: 1.0.0
servers:
  - url: /api
tags:
  - name: chat
    description: Chat endpoint
paths:
  /chat:
    post:
      tags:
        - chat
      summary: Chat endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatInput'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatOutput'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
    delete:
      tags:
        - chat
      summary: Delete chat endpoint
      responses:
        '204':
          description: Successful response
  /travel/departures:
    get:
      tags:
        - travel
      summary: Departures endpoint
      parameters:
        - name: station
          in: query
          required: true
          schema:
            type: string
        - name: count
          in: query
          required: false
          schema:
            type: integer
        - name: departureTime
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: addJourneys
          in: query
          required: false
          schema:
            type: boolean
        - name: country
          in: query
          required: false
          schema:
            type: string
            enum:
              - nl
              - be
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Departures'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /travel/journey:
    get:
      tags:
        - travel
      summary: Journey endpoint
      parameters:
        - name: station
          in: query
          required: true
          schema:
            type: string
        - name: trainNumber
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Journey'
        '400':
          description: Invalid request
components:
  schemas:
    ChatInput:
      type: object
      properties:
        chat:
          type: string
      required:
        - chat
    ChatOutput:
      type: object
      properties:
        chat:
          type: string
      required:
        - chat
    Departure:
      type: object
      properties:
        trainNumber:
          type: string
        destination:
          type: string
        departureTime:
          type: string
          format: date-time
        delay:
          type: integer
          format: int32
        track:
          type: string
        category:
          type: string
        cancelled:
          type: boolean
        trainType:
            type: string
        trainLength:
          type: integer
          format: int32
        numberOfSeats:
          type: integer
          format: int32
        stockIdentifiers:
          type: array
          items:
            type: string
        stockImageUris:
          type: array
          items:
            type: string
        crowdForecast:
          type: string
          enum:
            - UNKNOWN
            - LOW
            - MEDIUM
            - HIGH
        via:
          type: array
          items:
            type: string
        departureStatus:
          $ref: '#/components/schemas/DepartureStatusEnum'
        message:
          type: string
    DepartureStatusEnum:
      type: string
      enum:
        - ON_STATION
        - INCOMING
        - DEPARTED
        - UNKNOWN
    Departures:
      type: array
      items:
        $ref: '#/components/schemas/Departure'
    Journey:
      type: object
      properties:
        origin:
          type: string
        destination:
          type: string
        category:
          type: string
        cancelled:
          type: boolean
        trainType:
          type: string
        trainLength:
          type: integer
          format: int64
        numberOfSeats:
          type: integer
          format: int64
        stockIdentifiers:
          type: array
          items:
            type: string
        stockImageUris:
          type: array
          items:
            type: string
        crowdForecast:
          type: string
          enum:
            - UNKNOWN
            - LOW
            - MEDIUM
            - HIGH
        stops:
          type: array
          items:
            type: string
    Error:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
          format: int32
        code:
          type: string
        message:
          type: string
        traceId:
          type: string
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ServiceUnavailable:
      description: Service Unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'