package nl.markpost.aiassistant.constant;

public enum NSStationCode {
  AALTEN("Atn", "Aalten"),
  ABCOUDE("Ac", "Abcoude"),
  AKKRUM("Akm", "Akkrum"),
  ALKMAAR("Amr", "Alkmaar"),
  ALKMAAR_NOORD("Amrn", "Alkmaar Noord"),
  ALMELO("Aml", "Almelo"),
  ALMELO_DE_RIET("Amri", "Almelo de Riet"),
  ALMERE_BUITEN("Almb", "Almere Buiten"),
  ALMERE_CENTRUM("Alm", "Almere Centrum"),
  ALMERE_MUZIEKWIJK("Almm", "Almere Muziekwijk"),
  ALMERE_OOSTVAARDERS("Almo", "Almere Oostvaarders"),
  ALMERE_PARKWIJK("Almp", "Almere Parkwijk"),
  ALMERE_POORT("Ampo", "Almere Poort"),
  ALPHEN_AAN_DEN_RIJN("Apn", "Alphen aan den Rijn"),
  AMERSFOORT_CENTRAAL("Amf", "Amersfoort Centraal"),
  AMERSFOORT_SCHOTHORST("Amfs", "Amersfoort Schothorst"),
  AMERSFOORT_VATHORST("Avat", "Amersfoort Vathorst"),
  AMSTERDAM_AMSTEL("Asa", "Amsterdam Amstel"),
  AMSTERDAM_BIJLMER_ARENA("Asb", "Amsterdam Bijlmer ArenA"),
  AMSTERDAM_CENTRAAL("Asd", "Amsterdam Centraal"),
  AMSTERDAM_HOLENDRECHT("Asdh", "Amsterdam Holendrecht"),
  AMSTERDAM_LELYLAAN("Asdl", "Amsterdam Lelylaan"),
  AMSTERDAM_MUIDERPOORT("Asdm", "Amsterdam Muiderpoort"),
  AMSTERDAM_RAI("Rai", "Amsterdam RAI"),
  AMSTERDAM_SCIENCE_PARK("Assp", "Amsterdam Science Park"),
  AMSTERDAM_SLOTEDIJK("Ass", "Amsterdam Sloterdijk"),
  AMSTERDAM_ZUID("Asdz", "Amsterdam Zuid"),
  ANNA_PAULOWNA("Ana", "Anna Paulowna"),
  APELDOORN("Apd", "Apeldoorn"),
  APELDOORN_DE_MATEN("Apdm", "Apeldoorn De Maten"),
  APELDOORN_OSSEVELD("Apdo", "Apeldoorn Osseveld"),
  APPINGEDAM("Apg", "Appingedam"),
  ARKEL("Akl", "Arkel"),
  ARNEMUIDEN("Arn", "Arnemuiden"),
  ARNHEM_CENTRAAL("Ah", "Arnhem Centraal"),
  ARNHEM_PRESIKHAAF("Ahpr", "Arnhem Presikhaaf"),
  ARNHEM_VELPERPOORT("Ahp", "Arnhem Velperpoort"),
  ARNHEM_ZUID("Ahz", "Arnhem Zuid"),
  ASSEN("Asn", "Assen"),
  BAARN("Brn", "Baarn"),
  BAFLO("Bf", "Baflo"),
  BARENDRECHT("Brd", "Barendrecht"),
  BARNEVELD_CENTRUM("Bnc", "Barneveld Centrum"),
  BARNEVELD_NOORD("Bnn", "Barneveld Noord"),
  BEDUM("Bdm", "Bedum"),
  BEEK_ELSLOO("Bk", "Beek-Elsloo"),
  BEESD("Bsd", "Beesd"),
  BEILEN("Bl", "Beilen"),
  BERGEN_OP_ZOOM("Bgn", "Bergen op Zoom"),
  BEST("Bet", "Best"),
  BEVERWIJK("Bv", "Beverwijk"),
  BILTHOVEN("Bhv", "Bilthoven"),
  BLERICK("Br", "Blerick"),
  BLOEMENDAAL("Bll", "Bloemendaal"),
  BODEGRAVEN("Bdg", "Bodegraven"),
  BORNE("Bn", "Borne"),
  BOSKOOP("Bsk", "Boskoop"),
  BOSKOOP_SNIJDELWIJK("Bsks", "Boskoop Snijdelwijk"),
  BOVEN_HARDINXVELD("Bhdv", "Boven-Hardinxveld"),
  BOVENKARSPEL_FLORA("Bkf", "Bovenkarspel Flora"),
  BOVENKARSPEL_GROOTEBROEK("Bkg", "Bovenkarspel-Grootebroek"),
  BOXMEER("Bmr", "Boxmeer"),
  BOXTEL("Btl", "Boxtel"),
  BREDA("Bd", "Breda"),
  BREDA_PRINSENBEEK("Bdpb", "Breda-Prinsenbeek"),
  BREUKELEN("Bkl", "Breukelen"),
  BRUMMEN("Bmn", "Brummen"),
  BUITENPOST("Bp", "Buitenpost"),
  BUNDE("Bde", "Bunde"),
  BUNNIK("Bnk", "Bunnik"),
  BUSSUM_ZUID("Bsmz", "Bussum Zuid"),
  CAPELLE_SCHOLLEVAAR("Cps", "Capelle Schollevaar"),
  CASTRICUM("Cas", "Castricum"),
  CHEVREMONT("Cvm", "Chevremont"),
  COEVORDEN("Co", "Coevorden"),
  CUIJK("Ck", "Cuijk"),
  CULEMBORG("Cl", "Culemborg"),
  DAARLERVEEN("Da", "Daarlerveen"),
  DALEN("Dln", "Dalen"),
  DALFSEN("Dl", "Dalfsen"),
  DE_VINK("Dvnk", "De Vink"),
  DEINUM("Dei", "Deinum"),
  DELDEN("Ddn", "Delden"),
  DELFT("Dt", "Delft"),
  DELFT_CAMPUS("Dtz", "Delft Campus"),
  DELFZIJL("Dz", "Delfzijl"),
  DELFZIJL_WEST("Dzw", "Delfzijl West"),
  DEN_DOLDER("Dld", "Den Dolder"),
  DEN_HAAG_CENTRAAL("Gvc", "Den Haag Centraal"),
  DEN_HAAG_HS("Gv", "Den Haag HS"),
  DEN_HAAG_LAAN_VAN_NOI("Laa", "Den Haag Laan van NOI"),
  DEN_HAAG_MARIAHOEVE("Gvm", "Den Haag Mariahoeve"),
  DEN_HAAG_MOERWIJK("Gvmw", "Den Haag Moerwijk"),
  DEN_HAAG_YPENBURG("Ypb", "Den Haag Ypenburg"),
  DEN_HELDER("Hdr", "Den Helder"),
  DEN_HELDER_ZUID("Hdrz", "Den Helder Zuid"),
  DEURNE("Dn", "Deurne"),
  DEVENTER("Dv", "Deventer"),
  DEVENTER_COLMSCHATE("Dvc", "Deventer Colmschate"),
  DE_WESTEREEN("Dwe", "De Westereen"),
  DIDAM("Did", "Didam"),
  DIEMEN("Dmn", "Diemen"),
  DIEMEN_ZUID("Dmnz", "Diemen Zuid"),
  DIEREN("Dr", "Dieren"),
  DOETINCHEM("Dtc", "Doetinchem"),
  DOETINCHEM_DE_HUET("Dtch", "Doetinchem De Huet"),
  DORDRECHT("Ddr", "Dordrecht"),
  DORDRECHT_STADSPOLDERS("Ddrs", "Dordrecht Stadspolders"),
  DORDRECHT_ZUID("Ddzd", "Dordrecht Zuid"),
  DRIEBERGEN_ZEIST("Db", "Driebergen-Zeist"),
  DRIEHUIS("Drh", "Driehuis"),
  DRONRYP("Drp", "Dronryp"),
  DRONTEN("Dron", "Dronten"),
  DUIVEN("Dvn", "Duiven"),
  DUIVENDRECHT("Dvd", "Duivendrecht"),
  ECHT("Ec", "Echt"),
  EDE_CENTRUM("Edc", "Ede Centrum"),
  EDE_WAGENINGEN("Ed", "Ede-Wageningen"),
  EEMSHAVEN("Eem", "Eemshaven"),
  EIJDEN("Edn", "Eijsden"),
  EINDHOVEN_CENTRAAL("Ehv", "Eindhoven Centraal"),
  EINDHOVEN_STRIJP_S("Ehs", "Eindhoven Strijp-S"),
  ELST("Est", "Elst"),
  EMMEN("Emn", "Emmen"),
  EMMEN_ZUID("Emnz", "Emmen Zuid"),
  ENKHUIZEN("Ekz", "Enkhuizen"),
  ENSCHEDE("Es", "Enschede"),
  ENSCHEDE_DE_ESCHMARKE("Ese", "Enschede De Eschmarke"),
  ENSCHEDE_KENNISPARK("Esk", "Enschede Kennispark"),
  ERMELO("Eml", "Ermelo"),
  ETTEN_LEUR("Etn", "Etten-Leur"),
  EYGELSHOVEN("Egh", "Eygelshoven"),
  EYGELSHOVEN_MARKT("Eghm", "Eygelshoven Markt"),
  FEANWALDEN("Fwd", "Feanwâlden"),
  FRANEKER("Fn", "Franeker"),
  GAANDEREN("Gdr", "Gaanderen"),
  GELDERMALSEN("Gdm", "Geldermalsen"),
  GELDROP("Gp", "Geldrop"),
  GELEEN_OOST("Gln", "Geleen Oost"),
  GELEEN_LUTTERADE("Lut", "Geleen-Lutterade"),
  GILZE_RIJEN("Gz", "Gilze-Rijen"),
  GLANERBRUG("Gbr", "Glanerbrug"),
  GOES("Gs", "Goes"),
  GOOR("Go", "Goor"),
  GORINCHEM("Gr", "Gorinchem"),
  GOUDA("Gd", "Gouda"),
  GOUDA_GOVERWELLE("Gdg", "Gouda Goverwelle"),
  GRAMSBERGEN("Gbg", "Gramsbergen"),
  GRIJPSKERK("Gk", "Grijpskerk"),
  GRONINGEN("Gn", "Groningen"),
  GRONINGEN_EUROPAPARK("Gerp", "Groningen Europapark"),
  GRONINGEN_NOORD("Gnn", "Groningen Noord"),
  GROU_JIRNSUM("Gw", "Grou-Jirnsum"),
  HAARLEM("Hlm", "Haarlem"),
  HAARLEM_SPAARNWOUDE("Hlms", "Haarlem Spaarnwoude"),
  HALFWAY_ZWANENBURG("Hwzw", "Halfweg-Zwanenburg"),
  HARDENBERG("Hdb", "Hardenberg"),
  HARDERWIJK("Hd", "Harderwijk"),
  HARDINXVELD_BLAUWE_ZOOM("Hbzm", "Hardinxveld Blauwe Zoom"),
  HARDINXVELD_GIESSENDAM("Gnd", "Hardinxveld-Giessendam"),
  HAREN("Hrn", "Haren"),
  HARLINGEN("Hlg", "Harlingen"),
  HARLINGEN_HAVEN("Hlgh", "Harlingen Haven"),
  HEEMSKERK("Hk", "Heemskerk"),
  HEEMSTEDE_AERDENHOUT("Had", "Heemstede-Aerdenhout"),
  HEERENVEEN("Hr", "Heerenveen"),
  HEERENVEEN_IJSSTADION("Hrij", "Heerenveen IJsstadion"),
  HEERHUGOWAARD("Hwd", "Heerhugowaard"),
  HEERLEN("Hrl", "Heerlen"),
  HEERLEN_WOONBOULEVARD("Hrlw", "Heerlen Woonboulevard"),
  HEEZE("Hze", "Heeze"),
  HEILOO("Hlo", "Heiloo"),
  HEINO("Hno", "Heino"),
  HELMOND("Hm", "Helmond"),
  HELMOND_BRANDEVOORT("Hmbv", "Helmond Brandevoort"),
  HELMOND_BROUWHUIS("Hmbh", "Helmond Brouwhuis"),
  HELMOND_T_HOUT("Hmh", "Helmond 't Hout"),
  HEMMEN_DODEWAARD("Hmn", "Hemmen-Dodewaard"),
  HENGELO("Hgl", "Hengelo"),
  HENGELO_GEZONDHEIDSPARK("Hglg", "Hengelo Gezondheidspark"),
  HENGELO_OOST("Hglo", "Hengelo Oost"),
  S_HERTOGENBOSCH("Ht", "'s-Hertogenbosch"),
  S_HERTOGENBOSCH_OOST("Hto", "'s-Hertogenbosch Oost"),
  HILLEGOM("Hil", "Hillegom"),
  HILVERSUM("Hvs", "Hilversum"),
  HILVERSUM_NOORD("Hvsn", "Hilversum Noord"),
  HILVERSUM_SPORTPARK("Hvsp", "Hilversum Sportpark"),
  HINDELOOPEN("Hnp", "Hindeloopen"),
  HOENSBROEK("Hb", "Hoensbroek"),
  HOEVELAKEN("Hvl", "Hoevelaken"),
  HOLLANDSCHE_RADING("Hor", "Hollandsche Rading"),
  HOLTEN("Hon", "Holten"),
  HOOFDDORP("Hfd", "Hoofddorp"),
  HOOGEVEEN("Hgv", "Hoogeveen"),
  HOOGEZAND_SAPPEMEER("Hgz", "Hoogezand-Sappemeer"),
  HOOGKARSPEL("Hks", "Hoogkarspel"),
  HOORN("Hn", "Hoorn"),
  HOORN_KERSENBOOGERD("Hnk", "Hoorn Kersenboogerd"),
  HORST_SEVENUM("Hrt", "Horst-Sevenum"),
  HOUTEN("Htn", "Houten"),
  HOUTEN_CASTELLUM("Htnc", "Houten Castellum"),
  HOUTHEM_ST_GERLACH("Sgl", "Houthem-St. Gerlach"),
  HURDEGARYP("Hdg", "Hurdegaryp"),
  IJLST("IJt", "IJlst"),
  KAMPEN("Kpn", "Kampen"),
  KAMPEN_ZUID("Kpnz", "Kampen Zuid"),
  KAPELLE_BIEZELINGE("Bzl", "Kapelle-Biezelinge"),
  KERKRADE_CENTRUM("Krd", "Kerkrade Centrum"),
  KESTEREN("Ktr", "Kesteren"),
  KLARENBEEK("Kbk", "Klarenbeek"),
  KLIMMEN_RANSDAAL("Kmr", "Klimmen-Ransdaal"),
  KOOG_AAN_DE_ZAAN("Kz", "Koog aan de Zaan"),
  KOUDUM_MOLKWERUM("Kmw", "Koudum-Molkwerum"),
  KRABBENDIJKE("Kbd", "Krabbendijke"),
  KROMMENIE_ASSENDELFT("Kma", "Krommenie-Assendelft"),
  KROPSWOLDE("Kw", "Kropswolde"),
  KRUININGEN_YERSEKE("Krg", "Kruiningen-Yerseke"),
  LAGE_ZWALUWE("Zlw", "Lage Zwaluwe"),
  LANDGRAAF("Lg", "Landgraaf"),
  LANSINGERLAND_ZOETERMEER("Llzm", "Lansingerland-Zoetermeer"),
  LEERDAM("Ldm", "Leerdam"),
  LEEUWARDEN("Lw", "Leeuwarden"),
  LEEUWARDEN_CAMMINGHABUREN("Lwc", "Leeuwarden Camminghaburen"),
  LEIDEN_CENTRAAL("Ledn", "Leiden Centraal"),
  LEIDEN_LAMMENSCHANS("Ldl", "Leiden Lammenschans"),
  LELYSTAD_CENTRUM("Lls", "Lelystad Centrum"),
  LICHTENVOORDE_GROENLO("Ltv", "Lichtenvoorde-Groenlo"),
  LOCHEM("Lc", "Lochem"),
  LOPPERSUM("Lp", "Loppersum"),
  LUNTEREN("Ltn", "Lunteren"),
  MAARHEEZE("Mz", "Maarheeze"),
  MAARN("Mrn", "Maarn"),
  MAARSSEN("Mas", "Maarssen"),
  MAASTRICHT("Mt", "Maastricht"),
  MAASTRICHT_NOORD("Mtn", "Maastricht Noord"),
  MAASTRICHT_RANDWYCK("Mtr", "Maastricht Randwyck"),
  MANTGUM("Mg", "Mantgum"),
  MARIENBERG("Mrb", "Mariënberg"),
  MARTENSHOEK("Mth", "Martenshoek"),
  MEERSSEN("Mes", "Meerssen"),
  MEPPEL("Mp", "Meppel"),
  MIDDELBURG("Mdb", "Middelburg"),
  MOOK_MOLENHOEK("Mmlh", "Mook-Molenhoek"),
  NAARDEN_BUSSUM("Ndb", "Naarden-Bussum"),
  NIEUW_AMSTERDAM("Na", "Nieuw Amsterdam"),
  NIEUW_VENNEP("Nvp", "Nieuw Vennep"),
  NIEUWERKERK_AAN_DEN_IJSSEL("Nwk", "Nieuwerkerk aan den IJssel"),
  BAD_NIEUWESCHANS("Nsch", "Bad Nieuweschans"),
  NIJKERK("Nkk", "Nijkerk"),
  NIJMEGEN("Nm", "Nijmegen"),
  NIJMEGEN_DUKENBURG("Nmd", "Nijmegen Dukenburg"),
  NIJMEGEN_GOFFERT("Nmgo", "Nijmegen Goffert"),
  NIJMEGEN_HEYENDAAL("Nmh", "Nijmegen Heyendaal"),
  NIJMEGEN_LENT("Nml", "Nijmegen Lent"),
  NIJVERDAL("Nvd", "Nijverdal"),
  NUNSPEET("Ns", "Nunspeet"),
  NUTH("Nh", "Nuth"),
  OBDAM("Obd", "Obdam"),
  OISTERWIJK("Ot", "Oisterwijk"),
  OLDENZAAL("Odz", "Oldenzaal"),
  OLST("Ost", "Olst"),
  OMMEN("Omn", "Ommen"),
  OOSTERBEEK("Otb", "Oosterbeek"),
  OPHEUSDEN("Op", "Opheusden"),
  OSS("O", "Oss"),
  OSS_WEST("Ow", "Oss West"),
  OUDENBOSCH("Odb", "Oudenbosch"),
  OVERVEEN("Ovn", "Overveen"),
  PURMEREND("Pmr", "Purmerend"),
  PURMEREND_OVERWHERE("Pmo", "Purmerend Overwhere"),
  PURMEREND_WEIDEVENNE("Pmw", "Purmerend Weidevenne"),
  PUTTEN("Pt", "Putten"),
  RAALTE("Rat", "Raalte"),
  RAVENSTEIN("Rvs", "Ravenstein"),
  REUVER("Rv", "Reuver"),
  RHEDEN("Rh", "Rheden"),
  RHENEN("Rhn", "Rhenen"),
  RIJSSEN("Rsn", "Rijssen"),
  RIJSWIJK("Rsw", "Rijswijk"),
  RILLAND_BATH("Rb", "Rilland-Bath"),
  ROERMOND("Rm", "Roermond"),
  ROODESCHOOL("Rd", "Roodeschool"),
  ROOSENDAAL("Rsd", "Roosendaal"),
  ROSMALEN("Rs", "Rosmalen"),
  ROTTERDAM_ALEXANDER("Rta", "Rotterdam Alexander"),
  ROTTERDAM_BLAAK("Rtb", "Rotterdam Blaak"),
  ROTTERDAM_CENTRAAL("Rtd", "Rotterdam Centraal"),
  ROTTERDAM_LOMBARDIJEN("Rlb", "Rotterdam Lombardijen"),
  ROTTERDAM_NOORD("Rtn", "Rotterdam Noord"),
  ROTTERDAM_STADION("Rtst", "Rotterdam Stadion"),
  ROTTERDAM_ZUID("Rtz", "Rotterdam Zuid"),
  RUURLO("Rl", "Ruurlo"),
  SANTPOORT_NOORD("Sptn", "Santpoort Noord"),
  SANTPOORT_ZUID("Sptz", "Santpoort Zuid"),
  SAPPEMEER_OOST("Spm", "Sappemeer Oost"),
  SASSENHEIM("Ssh", "Sassenheim"),
  SAUWERD("Swd", "Sauwerd"),
  SCHAGEN("Sgn", "Schagen"),
  SCHEEMDA("Sda", "Scheemda"),
  SCHIEDAM_CENTRUM("Sdm", "Schiedam Centrum"),
  SCHINNEN("Sn", "Schinnen"),
  SCHIN_OP_GEUL("Sog", "Schin op Geul"),
  SCHIPHOL_AIRPORT("Shl", "Schiphol Airport"),
  SITTARD("Std", "Sittard"),
  SNEEK("Sk", "Sneek"),
  SNEEK_NOORD("Sknd", "Sneek Noord"),
  SOEST("St", "Soest"),
  SOEST_ZUID("Stz", "Soest Zuid"),
  SOESTDIJK("Sd", "Soestdijk"),
  SLIEDRECHT_BAANHOEK("Sdtb", "Sliedrecht Baanhoek"),
  SPAUBEEK("Sbk", "Spaubeek"),
  STAVOREN("Stv", "Stavoren"),
  STEDUM("Stm", "Stedum"),
  STEENWIJK("Swk", "Steenwijk"),
  SUSTEREN("Srn", "Susteren"),
  SWALMEN("Sm", "Swalmen"),
  TEGELEN("Tg", "Tegelen"),
  TERBORG("Tbg", "Terborg"),
  TIEL("Tl", "Tiel"),
  TIEL_PASSEWAAIJ("Tpsw", "Tiel Passewaaij"),
  TILBURG("Tb", "Tilburg"),
  TILBURG_REESHOF("Tbr", "Tilburg Reeshof"),
  TILBURG_UNIVERSITEIT("Tbu", "Tilburg Universiteit"),
  TWELLO("Twl", "Twello"),
  UITGEEST("Utg", "Uitgeest"),
  UITHUIZEN("Uhz", "Uithuizen"),
  UITHUIZERMEEDEN("Uhm", "Uithuizermeeden"),
  USQUERT("Ust", "Usquert"),
  UTRECHT_CENTRAAL("Ut", "Utrecht Centraal"),
  UTRECHT_LEIDSCHE_RIJN("Utlr", "Utrecht Leidsche Rijn"),
  UTRECHT_LUNETTEN("Utln", "Utrecht Lunetten"),
  UTRECHT_MALIEBAAN("Utm", "Utrecht Maliebaan"),
  UTRECHT_OVERVECHT("Uto", "Utrecht Overvecht"),
  UTRECHT_TERWIJDE("Utt", "Utrecht Terwijde"),
  UTRECHT_VAARTSCHE_RIJN("Utvr", "Utrecht Vaartsche Rijn"),
  UTRECHT_ZUILEN("Utzl", "Utrecht Zuilen"),
  VALKENBURG("Vk", "Valkenburg"),
  VARSSEVELD("Vsv", "Varsseveld"),
  VEENDAM("Vdm", "Veendam"),
  VEENENDAAL_CENTRUM("Vndc", "Veenendaal Centrum"),
  VEENENDAAL_DE_KLOMP("Klp", "Veenendaal-De Klomp"),
  VEENENDAAL_WEST("Vndw", "Veenendaal West"),
  VELP("Vp", "Velp"),
  VENLO("Vl", "Venlo"),
  VENRAY("Vry", "Venray"),
  VIERLINGSBEEK("Vlb", "Vierlingsbeek"),
  VLEUTEN("Vtn", "Vleuten"),
  VLISSINGEN("Vs", "Vlissingen"),
  VLISSINGEN_SOUBURG("Vss", "Vlissingen Souburg"),
  VOERENDAAL("Vdl", "Voerendaal"),
  VOORBURG("Vb", "Voorburg"),
  VOORHOUT("Vh", "Voorhout"),
  VOORSCHOTEN("Vst", "Voorschoten"),
  VOORST_EMPE("Vem", "Voorst-Empe"),
  VORDEN("Vd", "Vorden"),
  VRIEZENVEEN("Vz", "Vriezenveen"),
  VROOMSHOOP("Vhp", "Vroomshoop"),
  VUGHT("Vg", "Vught"),
  WADDINXVEEN("Wad", "Waddinxveen"),
  WADDINXVEEN_NOORD("Wadn", "Waddinxveen Noord"),
  WADDINXVEEN_TRIANGEL("Wadt", "Waddinxveen Triangel"),
  WARFFUM("Wfm", "Warffum"),
  WEERT("Wt", "Weert"),
  WEESP("Wp", "Weesp"),
  WEHL("Wl", "Wehl"),
  WESTERVOORT("Wtv", "Westervoort"),
  WEZEP("Wz", "Wezep"),
  WIERDEN("Wdn", "Wierden"),
  WIJCHEN("Wc", "Wijchen"),
  WIJHE("Wh", "Wijhe"),
  WINSCHOTEN("Ws", "Winschoten"),
  WINSUM("Wsm", "Winsum"),
  WINTERSWIJK("Ww", "Winterswijk"),
  WINTERSWIJK_WEST("Www", "Winterswijk West"),
  WOERDEN("Wd", "Woerden"),
  WOLFHEZE("Wf", "Wolfheze"),
  WOLVEGA("Wv", "Wolvega"),
  WORKUM("Wk", "Workum"),
  WORMERVEER("Wm", "Wormerveer"),
  ZAANDAM("Zd", "Zaandam"),
  ZAANDAM_KOGERVELD("Zdk", "Zaandam Kogerveld"),
  ZALTBOMMEL("Zbm", "Zaltbommel"),
  ZANDVOORT_AAN_ZEE("Zvt", "Zandvoort aan Zee"),
  ZETTEN_ANDELST("Za", "Zetten-Andelst"),
  ZEVENAAR("Zv", "Zevenaar"),
  ZEVENBERGEN("Zvb", "Zevenbergen"),
  ZOETERMEER("Ztm", "Zoetermeer"),
  ZOETERMEER_OOST("Ztmo", "Zoetermeer Oost"),
  ZUIDBROEK("Zb", "Zuidbroek"),
  ZUIDHORN("Zh", "Zuidhorn"),
  ZUTPHEN("Zp", "Zutphen"),
  ZWIJNDRECHT("Zwd", "Zwijndrecht"),
  ZWOLLE("Zl", "Zwolle"),
  ZWOLLE_STADSHAGEN("Zlsh", "Zwolle Stadshagen"),
  ZAANDIJK_ZAANSE_SCHANS("Zzs", "Zaandijk Zaanse Schans");

  private final String code;
  private final String name;

  NSStationCode(String code, String name) {
    this.code = code;
    this.name = name;
  }

  public String getCode() {
    return code;
  }

  public String getName() {
    return name;
  }

  public static NSStationCode getByName(String name) {
    for (NSStationCode station : values()) {
      if (station.getName().equalsIgnoreCase(name)) {
        return station;
      }
    }
    throw new IllegalArgumentException("No enum constant with name " + name);
  }
}
